part of monadart;

/// Represents a single HTTP request.
///
/// Contains a standard library [HttpRequest], along with other values
/// to associate data with a request.
class ResourceRequest {

  /// The internal [HttpRequest] of this [ResourceRequest].
  ///
  /// The standard library generated HTTP request object. This contains
  /// all of the request information provided by the client.
  final HttpRequest request;


  /// The response object of this [ResourceRequest].
  ///
  /// To respond to a request, this object must be written to. It is the same
  /// instance as the [request]'s response.
  HttpResponse get response => request.response;

  /// The extracted variable parameters from the URI of this request.
  ///
  /// Typically set by a [Router] instance when the request has been piped through one,
  /// this map will contain the values for any variables in a request URI. If generated by a [Router], will not contain
  /// constant strings from the URI. For example, if the path '/users/:id' and a the request URI path is '/users/1',
  /// this will be {"id" : 1}.
  Map<String, String> pathParameters = null;

  /// Optional data for members of a pipeline to attach to a request for later members to utilize.
  ///
  /// This is purely contextual to the application. An example is pipeline that adds a database adapter
  /// to the request so that the handling [ResourceController] has access to it.
  Map<dynamic, dynamic> context = new Map();

  ResourceRequest(this.request) {

  }

}